import { ArrowRight, BookOpen, Check, Code2, Compass, Github, Layers3, Sparkles, UserRound, Clock3 } from 'lucide-react';
import { domainLabels, levelLabels, type PublicState } from '../shared/schema';
export default function Home({ state, onProfile, onGenerate, onOpen, busy }: { state: PublicState; onProfile: () => void; onGenerate: () => void; onOpen: (id: string) => void; busy: boolean }) {
  const active = state.assignments[0];
  return <><div className="eyebrow">YOUR NEXT CHAPTER</div><div className="page-heading"><div><h1>{state.profile ? <>{state.profile.name}님의 경험을,<br/>다음 프로젝트로<span className="accent">.</span></> : <>나의 경험이,<br/>코드가 되는 곳<span className="accent">.</span></>}</h1><p className="lead">이미 알고 있는 것에서 시작하세요.<br/>나에게 맞는 실습으로 만들고, 원리까지 이해하는 바이브 코딩.</p></div><span className="chapter-index">{String(state.assignments.length + 1).padStart(2, '0')}<span>{active ? '이어가는 배움' : '시작하는 단계'}</span></span></div>
  <section className="welcome-card"><div><span className="pill"><Sparkles size={14}/> PERSONAL LEARNING PATH</span><h2>{active ? active.title : state.profile ? `${domainLabels[state.profile.domain]}, 나의 첫 프로젝트` : '누구나 같은 출발선일 필요는 없으니까.'}</h2><p>{active ? active.summary : state.profile ? `${state.profile.major} · ${state.profile.role} 경험에서 시작하는 맞춤 실습을 준비했어요.` : <>전공, 직무, 학습 스타일을 알려주면<br/>지금 나에게 필요한 프로젝트를 함께 설계해요.</>}</p><button className="primary" disabled={busy} onClick={active ? () => onOpen(active.id) : state.profile ? onGenerate : onProfile}>{busy ? '맞춤 과제를 설계하고 있어요…' : active ? '이어서 실습하기' : state.profile ? '나의 맞춤 과제 생성하기' : '나의 학습 프로필 만들기'} <ArrowRight size={18}/></button></div><div className="flow-visual" aria-label="경험, 실습, 이해로 이어지는 학습 과정"><div><UserRound size={18}/><span>나의 경험</span><small>전공 · 직무 · 관심사</small></div><span className="flow-line"/><div className="highlight"><Code2 size={20}/><span>맞춤 실습</span><small>나만의 프로젝트</small></div><span className="flow-line"/><div><BookOpen size={18}/><span>깊이 있는 이해</span><small>원리 · 이론 · 회고</small></div></div></section>
  {state.profile && <div className="stats"><div><span>함께 만든 과제</span><strong>{state.assignments.length}<small>개</small></strong></div><div><span>완료한 실습 단계</span><strong>{state.assignments.reduce((n,a) => n + a.completedSteps.length,0)}<small>단계</small></strong></div><div><span>회고를 남긴 프로젝트</span><strong>{state.assignments.filter(a => a.submission).length}<small>개</small></strong></div></div>}
  <div className="section-title"><h2>{state.assignments.length ? '나의 프로젝트' : '작게 만들고, 깊게 이해해요'}</h2>{state.assignments.length ? <button className="text-button" disabled={busy} onClick={onGenerate}><Sparkles size={15}/> 새 맞춤 과제</button> : <span>THE LEARNING LOOP</span>}</div>
  {state.assignments.length ? <div className="assignment-grid">{state.assignments.map(a => <button className="assignment-card" key={a.id} onClick={() => onOpen(a.id)}><div className="card-top"><span className="tag">{domainLabels[a.profile.domain]}</span><span>{a.source === 'ai' ? 'AI 생성' : '규칙 기반'}</span></div><h3>{a.title}</h3><p>{a.summary}</p><div className="metadata"><span><Clock3 size={14}/>{a.minutes}분 · {a.lessons.length}회</span><span>{levelLabels[a.difficulty]}</span></div><progress value={a.completedSteps.length} max={a.lessons.length}/><div className="card-bottom">{a.completedSteps.length}/{a.lessons.length} 단계 완료 <ArrowRight size={16}/></div></button>)}</div> : <div className="learning-grid">{[{icon:Compass,title:'나에게 맞는 시작',text:'배경지식과 학습 성향을 바탕으로 과제의 난이도와 설명 방식을 조절해요.'},{icon:Layers3,title:'실습과 원리를 함께',text:'프롬프트를 입력한 다음, 코드의 흐름을 따라가며 작동 이유를 확인해요.'},{icon:Github,title:'진짜 프로젝트로 연결',text:'GitHub의 실제 저장소를 살펴보고, 나의 결과물과 학습 기록을 남겨요.'}].map((item,i)=><article className="learning-card" key={item.title}><div className="card-top"><item.icon size={24}/><span>0{i+1}</span></div><h3>{item.title}</h3><p>{item.text}</p><span className="card-bottom"><Check size={14}/> 나의 속도에 맞춰 차근차근</span></article>)}</div>}</>;
}
