import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowUpRight, Search } from 'lucide-react';
import { disciplines, listExercises, recommendation, themes } from '../shared/catalog';
import type { PracticeAttempt, Profile } from '../shared/schema';
import CodeLab from './CodeLab';

export default function PracticeLibrary({profile,history}:{profile:Profile|null;history:PracticeAttempt[]}) {
  const [query,setQuery]=useState(''); const [discipline,setDiscipline]=useState('all'); const [theme,setTheme]=useState('all'); const [selected,setSelected]=useState('');
  const all=useMemo(()=>listExercises(),[]);
  const plan=profile?recommendation(profile):null;
  const exercise=all.find(e=>e.id===selected);
  const results=all.filter(e=>(discipline==='all'||e.disciplineId===discipline)&&(theme==='all'||e.theme===theme)&&`${e.title} ${e.objective} ${e.theory}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(plan?.exerciseIds.includes(b.id))-Number(plan?.exerciseIds.includes(a.id)));
  if(exercise)return <><button className="text-button" onClick={()=>setSelected('')}><ArrowLeft size={16}/> 실습 자료실로</button><h1 className="small-heading">{exercise.title}</h1><p className="lead">{exercise.objective}</p><section className="panel"><p>{exercise.theory}</p><CodeLab key={exercise.id} exercise={exercise}/><a href={exercise.referenceUrl} target="_blank" rel="noreferrer">관련 원리·오픈소스 참고 <ArrowUpRight size={14}/></a><p className="small-note">실행 예제는 Vibe Lab이 작성한 교육용 코드입니다. 참고 저장소 코드를 자동으로 내려받아 실행하지 않습니다.</p></section></>;
  return <><div className="eyebrow">ENGINEERING DATA LAB</div><h1 className="small-heading">내 분야의 데이터를 코드로 이해해요.</h1><p className="lead">전공별 데이터와 직무별 문제를 골라, 작은 함수부터 직접 완성해 보세요.</p>{plan&&<div className="recommendation"><strong>나의 추천 경로</strong><p>{plan.reason}</p></div>}{!profile&&<p className="small-note">프로필을 먼저 저장하면 맞춤 추천과 학습 기록 저장을 사용할 수 있습니다.</p>}<div className="library-filters"><label>전공·업무 분야<select value={discipline} onChange={e=>setDiscipline(e.target.value)}><option value="all">전체 분야</option>{[...disciplines,{id:'project',label:'프로젝트·생산 운영'}].map(d=><option key={d.id} value={d.id}>{d.label}</option>)}</select></label><label>학습 테마<select value={theme} onChange={e=>setTheme(e.target.value)}><option value="all">전체 테마</option>{themes.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select></label><label>실습 검색<span className="library-search"><Search size={16}/><input aria-label="실습 검색" value={query} maxLength={100} onChange={e=>setQuery(e.target.value)} placeholder="예: 진동, 누락, 비동기"/></span></label></div><p className="small-note">{results.length}개 실습 · 공통 데이터 처리 원리를 전공별 입력·단위·테스트에 적용합니다. 실험 범위는 교육용이며 산업 규격이 아닙니다.</p><div className="assignment-grid">{results.map(e=><button key={e.id} className="assignment-card" onClick={()=>setSelected(e.id)}><div className="card-top"><span className="tag">{themes.find(t=>t.id===e.theme)?.label}</span>{plan?.exerciseIds.includes(e.id)&&<span>프로필 추천</span>}</div><h3>{e.title}</h3><p>{e.objective}</p><div className="metadata"><span>빈칸 실습 · {e.tests.length}개 테스트</span><span>{e.sourceIds.length?'공개 GitHub 데이터 선택 가능':'합성 데이터'}</span></div><span className="card-bottom">{history.some(a=>a.exerciseId===e.id&&a.status==='passed')?'통과 기록 있음':'직접 실행하며 배우기'} <ArrowUpRight size={15}/></span></button>)}</div>{!results.length&&<p className="empty-state">검색어 또는 필터를 바꿔 보세요.</p>}</>;
}
