import { useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Sparkles } from 'lucide-react';
import { defaultProfile, domainLabels, levelLabels, profileSchema, styleLabels, type Profile as LearnerProfile } from '../shared/schema';
import { disciplines, personas, themes } from '../shared/catalog';
export default function Profile({ initial, onSave, busy }: { initial: LearnerProfile | null; onSave: (profile: LearnerProfile) => Promise<void>; busy: boolean }) {
  const [profile, setProfile] = useState<LearnerProfile>(initial || {...defaultProfile, personaId:'engineer', domain:'data', major:'', role:'엔지니어', goal:'업무 데이터를 정제하고 결과를 비교하는 코드를 직접 작성하고 이해하고 싶어요.', minutes:30});
  const [step, setStep] = useState(0); const [error, setError] = useState('');
  const update = <K extends keyof LearnerProfile>(key: K, value: LearnerProfile[K]) => setProfile(p => ({ ...p, [key]: value }));
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setError('');
    if (step < 2) { setStep(step + 1); return; }
    const result = profileSchema.safeParse(profile);
    if (!result.success) { setError('이름, 전공, 직무와 5자 이상의 목표를 입력해 주세요.'); return; }
    await onSave(result.data);
  }
  return <><div className="eyebrow">GET TO KNOW YOU</div><h1 className="small-heading">어떤 경험을 가지고 있나요?</h1><p className="lead">정답은 없어요. 지금의 나를 알려주면, 거기에 맞춰 시작할게요.</p><div className="profile-layout"><div className="profile-steps">{['나의 배경', '경험과 학습 스타일', '이번에 이루고 싶은 것'].map((label,i)=><button key={label} className={i === step ? 'selected' : ''} onClick={() => setStep(i)}><span>{i < step ? <Check size={16}/> : i + 1}</span>{label}</button>)}<p>입력한 정보는 맞춤 과제와 설명에 사용돼요. AI를 연결하면 이 정보가 AI 제공자에게 전달됩니다. 민감한 정보는 적지 마세요.</p></div><form className="panel profile-form" onSubmit={submit}><span className="eyebrow">STEP 0{step+1} / 03</span>
  {step === 0 && <><h2>이미 알고 있는 것이 좋은 출발점이에요.</h2><label>학습 상황<input list="persona-options" maxLength={80} value={personas.find(p=>p.id===profile.personaId)?.label || profile.personaId || ''} onChange={e=>update('personaId',personas.find(p=>p.label===e.target.value)?.id || e.target.value || undefined)} placeholder="대학생, 실무 엔지니어 또는 직접 입력"/><datalist id="persona-options">{personas.map(p=><option key={p.id} value={p.label}/>)}</datalist></label><label>실습에 연결할 전공 분야<select value={profile.disciplineId || ''} onChange={e=>update('disciplineId',e.target.value || undefined)}><option value="">전공 입력으로 추천</option>{disciplines.map(d=><option key={d.id} value={d.id}>{d.label}</option>)}</select></label><div className="form-row"><label>전공 또는 익숙한 분야<input required maxLength={80} value={profile.major} onChange={e => update('major', e.target.value)} placeholder="예: 전자공학, 기계공학, 화학, 생명과학"/></label><label>현재 직무 또는 하는 일<input required maxLength={80} value={profile.role} onChange={e => update('role', e.target.value)} placeholder="예: 연구개발 및 PM, 품질 엔지니어, 대학생"/></label></div><label>어떤 분야를 만들어 볼까요?<select value={profile.domain} onChange={e => update('domain', e.target.value as LearnerProfile['domain'])}>{Object.entries(domainLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></>}
  {step === 1 && <><h2>나에게 편한 속도와 방식을 찾아요.</h2><fieldset><legend>코딩은 얼마나 해봤나요?</legend><div className="choice-list">{Object.entries(levelLabels).map(([value,label])=><label className={profile.level === value ? 'choice selected' : 'choice'} key={value}><input type="radio" name="level" checked={profile.level === value} onChange={() => update('level',value as LearnerProfile['level'])}/>{label}</label>)}</div></fieldset><fieldset><legend>익숙한 개념을 모두 골라주세요.</legend><div className="knowledge-list">{['html','javascript','react','api','sql','git'].map(value=><label key={value} className="check-chip"><input type="checkbox" checked={profile.knowledge.includes(value as LearnerProfile['knowledge'][number])} onChange={e => update('knowledge', e.target.checked ? [...profile.knowledge,value as LearnerProfile['knowledge'][number]] : profile.knowledge.filter(k => k !== value))}/>{value.toUpperCase()}</label>)}</div><small className="muted">처음이라면 선택하지 않아도 괜찮아요.</small></fieldset><label>어떻게 배우는 게 편한가요?<select value={profile.style} onChange={e=>update('style',e.target.value as LearnerProfile['style'])}>{Object.entries(styleLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></>}
  {step === 2 && <><h2>작지만 구체적인 목표를 알려주세요.</h2><fieldset><legend>우선 배우고 싶은 데이터 처리 (복수 선택)</legend><div className="knowledge-list">{themes.map(t=><label key={t.id} className="check-chip"><input type="checkbox" checked={profile.interests?.includes(t.id) || false} onChange={e=>update('interests',e.target.checked?[...(profile.interests || []),t.id]:(profile.interests || []).filter(id=>id!==t.id))}/>{t.label}</label>)}</div><p className="small-note">선택하지 않으면 직무와 목표에서 추천합니다.</p></fieldset><label>어떤 문제를 해결하고 싶나요?<textarea rows={5} required minLength={5} maxLength={500} value={profile.goal} onChange={e=>update('goal',e.target.value)} placeholder="예: 매주 반복하는 팀의 업무 요청 정리를 자동화하고 싶어요."/></label><label>한 번에 학습할 시간<select value={profile.minutes} onChange={e=>update('minutes',Number(e.target.value))}>{[20,30,45,60,90,120,180].map(v=><option key={v} value={v}>{v}분</option>)}</select></label><div className="notice"><Sparkles size={20}/><p>학습 결과에 따라 다음 과제의 난이도가 조정돼요. 프로필은 나중에 언제든 바꿀 수 있어요.</p></div></>}
  {error && <p role="alert" className="inline-error">{error}</p>}<div className="form-actions">{step > 0 && <button type="button" className="secondary" onClick={()=>setStep(step-1)}><ArrowLeft size={16}/> 이전</button>}<button className="primary" disabled={busy}>{busy ? '저장하는 중…' : step < 2 ? '다음으로' : '프로필 저장하기'}<ArrowRight size={16}/></button></div></form></div></>;
}
