import { useState } from 'react';
import { ArrowUpRight, BookOpen, Folder, Github, Search, Star } from 'lucide-react';
import type { Repository } from '../shared/schema';
import { api } from './api';
type Detail = {name:string; defaultBranch:string; pushedAt:string; license:string|null; isTemplate:boolean; readme:string; files:string[]; warnings:string[]};
const collections = [{name:'웹 개발 첫걸음',query:'Web-Dev-For-Beginners in:name',text:'기초 개념부터 작은 웹 프로젝트까지',repo:'microsoft/Web-Dev-For-Beginners'},{name:'실전 TypeScript',query:'typescript tutorial',text:'타입과 데이터 구조를 다루는 예제',repo:'microsoft/TypeScript'},{name:'API와 데이터 연결',query:'node express postgres example',text:'서버와 데이터베이스가 연결되는 방식',repo:'brianc/node-postgres'}];
export default function Repositories({onError,authenticated}:{onError:(v:string)=>void;authenticated:boolean}) {
  const [query,setQuery] = useState('react typescript tutorial'); const [results,setResults] = useState<Repository[]|null>(null); const [busy,setBusy] = useState(false); const [detail,setDetail] = useState<Detail|null>(null); const [loadingName,setLoadingName] = useState('');
  async function search(value:string) { if (busy) return; setQuery(value);setBusy(true);onError('');try{setResults(await api<Repository[]>(`/github/search?q=${encodeURIComponent(value)}`));}catch(e){onError((e as Error).message);}finally{setBusy(false);} }
  async function inspect(name:string) { setLoadingName(name);onError('');try{setDetail(await api<Detail>(`/github/repository?name=${encodeURIComponent(name)}`));}catch(e){onError((e as Error).message);}finally{setLoadingName('');} }
  return <><div className="eyebrow">LEARN FROM OPEN SOURCE</div><h1 className="small-heading">다른 사람의 코드에서 배워요.</h1><p className="lead">GitHub의 공개 저장소를 살펴보고, 나의 실습에 연결할 아이디어를 찾아보세요.</p><form className="search-form" onSubmit={e=>{e.preventDefault();void search(query);}}><Search size={21}/><input aria-label="GitHub 저장소 검색" required minLength={2} maxLength={120} value={query} onChange={e=>setQuery(e.target.value)} placeholder="예: react typescript tutorial"/><button className="primary" disabled={busy}>{busy?'검색 중…':'저장소 검색'}</button></form><p className="small-note">{authenticated?'서버 토큰으로 GitHub에 연결됩니다.':'공개 GitHub API를 사용합니다. 요청 한도에 도달하면 잠시 후 다시 시도해 주세요.'} 검색 결과는 최대 5분간 캐시돼요.</p>
  <div className="section-title"><h2>이 주제에서 시작해 보세요</h2><span>CURATED STARTING POINTS</span></div><div className="learning-grid">{collections.map(c=><div className="learning-card" key={c.name}><BookOpen size={22}/><h3>{c.name}</h3><p>{c.text}</p><div className="collection-actions"><button className="text-button" disabled={busy} onClick={()=>void search(c.query)}>관련 저장소 찾기 <ArrowUpRight size={15}/></button><button className="text-button" disabled={!!loadingName} onClick={()=>void inspect(c.repo)}>{loadingName===c.repo?'불러오는 중…':'대표 저장소 살펴보기'}</button></div></div>)}</div>
  {results!==null&&<><div className="section-title"><h2>검색 결과 <span className="muted">{results.length}</span></h2><span>GITHUB LIVE DATA</span></div>{results.length===0?<div className="empty-state"><Search size={28}/><p>결과가 없어요. 더 짧은 영어 키워드로 검색해 보세요.</p></div>:<div className="repo-grid">{results.map(repo=><article className="panel repo-card" key={repo.fullName}><div className="card-top"><Github size={23}/><span><Star size={14}/>{Intl.NumberFormat('ko-KR',{notation:'compact'}).format(repo.stars)}</span></div><h3><a href={repo.url} target="_blank" rel="noreferrer">{repo.fullName}<ArrowUpRight size={14}/></a></h3><p>{repo.description}</p><div className="metadata"><span>{repo.language||'언어 정보 없음'}</span><span>{repo.license||'라이선스 확인 필요'}</span></div><div className="card-bottom"><span>업데이트 {new Date(repo.updatedAt).toLocaleDateString('ko-KR')}</span><button className="text-button" disabled={!!loadingName} onClick={()=>void inspect(repo.fullName)}>{loadingName===repo.fullName?'불러오는 중…':'코드 구조 살펴보기'}</button></div></article>)}</div>}</>}
  {detail&&<section className="panel repository-detail" aria-label="저장소 상세"><div className="section-title"><h2>{detail.name}</h2><button className="secondary" onClick={()=>setDetail(null)}>닫기</button></div><div className="notice"><BookOpen size={20}/><p>코드를 재사용하기 전에 라이선스와 실행 방법을 확인하세요. 이 화면은 외부 README를 텍스트로 표시합니다.</p></div><div className="repo-links"><a className="secondary" target="_blank" rel="noreferrer" href={`https://github.com/${detail.name}`}>GitHub에서 열기 <ArrowUpRight size={15}/></a><a className="secondary" target="_blank" rel="noreferrer" href={`https://github.com/codespaces/new?repo=${encodeURIComponent(detail.name)}`}>Codespaces 설정 열기 <ArrowUpRight size={15}/></a>{detail.isTemplate&&<a className="secondary" target="_blank" rel="noreferrer" href={`https://github.com/${detail.name}/generate`}>템플릿으로 시작하기 <ArrowUpRight size={15}/></a>}</div><p className="small-note">Codespaces 생성은 GitHub에서 진행하며 계정의 사용 한도와 과금이 적용될 수 있어요.</p><div className="readme-layout"><div><h3>루트 파일 구조</h3><ul className="file-list">{detail.files.map(file=><li key={file}><Folder size={15}/>{file}</li>)}</ul><p className="small-note">라이선스: {detail.license||'확인 필요'}</p></div><div><h3>README 미리보기</h3><pre className="readme">{detail.readme||'README를 가져오지 못했습니다. GitHub에서 직접 확인해 주세요.'}</pre></div></div>{detail.warnings.map(w=><p className="inline-error" key={w}>{w}</p>)}</section>}
  </>;
}
