import { useState } from 'react';
import { ArrowRight, BookOpen, Check, CheckCircle2, Clock3, Copy, Download, FlaskConical, Github, Send, Sparkles } from 'lucide-react';
import { domainLabels, levelLabels, type Message, type PublicAssignment, type QuizResult, type Submission } from '../shared/schema';
import { api, downloadText } from './api';
import CodeLab from './CodeLab';
import { CATALOG_VERSION, getExercise } from '../shared/catalog';
export default function Workspace({ assignment: a, messages, aiEnabled, onError, onNotice, onUpdate, onMessages }: { assignment: PublicAssignment; messages: Message[]; aiEnabled: boolean; onError: (value:string)=>void; onNotice:(value:string)=>void; onUpdate:(value:PublicAssignment)=>void; onMessages:(value:Message[])=>void }) {
  const [tab,setTab] = useState<'practice'|'quiz'|'submit'>('practice');
  const [step,setStep] = useState(Math.max(0,a.lessons.findIndex((_l,i)=>!a.completedSteps.includes(i))));
  const [question,setQuestion] = useState(''); const [chatBusy,setChatBusy] = useState(false); const [busy,setBusy] = useState(false);
  const [answers,setAnswers] = useState<number[]>(Array(a.quiz.length).fill(-1));
  const [url,setUrl] = useState(a.submission?.url || ''); const [reflection,setReflection] = useState(a.submission?.reflection || '');
  const lesson = a.lessons[step];
  const exercise = a.practice?.catalogVersion === CATALOG_VERSION ? getExercise(a.practice.exerciseIds[step]) : undefined;
  async function progress() { setBusy(true); onError(''); try { onUpdate(await api<PublicAssignment>(`/assignments/${a.id}/progress`,{method:'PATCH',body:JSON.stringify({step,completed:!a.completedSteps.includes(step)})})); onNotice('진도를 저장했어요.'); } catch(e) { onError((e as Error).message); } finally { setBusy(false); } }
  async function chat(text: string) { if (!text.trim() || chatBusy) return; setChatBusy(true); onError(''); try { onMessages(await api<Message[]>(`/assignments/${a.id}/chat`,{method:'POST',body:JSON.stringify({message:text,lessonIndex:step})})); setQuestion(''); } catch(e) { onError((e as Error).message); } finally { setChatBusy(false); } }
  async function quiz(event: React.FormEvent) { event.preventDefault(); setBusy(true); onError(''); try { const result = await api<QuizResult>(`/assignments/${a.id}/quiz`,{method:'POST',body:JSON.stringify({answers})}); onUpdate({...a,quizResult:result}); onNotice('이해도 확인 결과를 저장했어요.'); } catch(e) { onError((e as Error).message); } finally { setBusy(false); } }
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); onError(''); try { const submission = await api<Submission>(`/assignments/${a.id}/submission`,{method:'POST',body:JSON.stringify({url,reflection})}); onUpdate({...a,submission}); onNotice('저장소 확인 결과와 회고를 저장했어요.'); } catch(e) { onError((e as Error).message); } finally { setBusy(false); } }
  function exportAssignment() { downloadText('vibe-lab-assignment.md',`# ${a.title}\n\n${a.summary}\n\n## 이 과제를 추천한 이유\n${a.rationale}\n\n`+a.lessons.map((l,i)=>`## ${i+1}. ${l.title}\n\n${l.objective}\n\n### 코딩 프롬프트\n${l.prompt}\n\n### 원리\n${l.theory}\n\n### 실험\n${l.experiment}\n\n${l.checks.map(c=>'- [ ] '+c).join('\n')}`).join('\n\n')+`\n\n## 학습 회고\n${a.submission?.reflection || '무엇을 만들었나요? 어떤 원리를 이해했나요? 다음에는 무엇을 바꾸고 싶나요?'}\n`); }
  const theory = <section className="theory-box"><h3><BookOpen size={18}/> 왜 이렇게 작동할까요?</h3><p>{lesson.theory}</p><a href={exercise ? exercise.referenceUrl : step===0?'https://www.typescriptlang.org/docs/handbook/2/everyday-types.html':step===1?'https://react.dev/learn/state-a-components-memory':step===2?'https://developer.mozilla.org/ko/docs/Web/HTTP/Overview':'https://www.postgresql.org/docs/current/tutorial.html'} target="_blank" rel="noreferrer">관련 공식 문서 읽기 <ArrowRight size={14}/></a></section>;
  return <><div className="eyebrow">BUILD · EXPERIMENT · UNDERSTAND</div><div className="workspace-heading"><h1 className="small-heading">{a.title}</h1><button className="secondary" onClick={exportAssignment}><Download size={16}/> 과제 내보내기</button></div><div className="metadata"><span className="tag">{domainLabels[a.profile.domain]}</span><span>{levelLabels[a.difficulty]}</span><span><Clock3 size={15}/>{a.minutes}분 · {a.lessons.length}회</span><span>{a.source==='ai'?'AI 생성 과제':'규칙 기반 과제'}</span></div><p className="lead">{a.summary}</p><details className="recommendation"><summary>이 과제가 나에게 맞는 이유</summary><p>{a.rationale}</p></details><div className="concept-list">{a.concepts.map((c,i)=><span key={`${c}-${i}`}>{c}</span>)}</div>
  <div className="tabs" aria-label="학습 화면">{([{id:'practice',label:'단계별 실습'},{id:'quiz',label:'이해도 확인'},{id:'submit',label:'GitHub 제출 · 회고'}] as const).map(t=><button key={t.id} aria-pressed={tab===t.id} className={tab===t.id?'active':''} onClick={()=>setTab(t.id)}>{t.label}</button>)}</div>
  {tab==='practice' && <div className="workspace-layout"><div className="lesson-column"><div className="step-list">{a.lessons.map((l,i)=><button key={i} className={step===i?'active':''} onClick={()=>setStep(i)} aria-current={step===i?'step':undefined}><span className={a.completedSteps.includes(i)?'done':''}>{a.completedSteps.includes(i)?<Check size={15}/>:i+1}</span><span>{l.title}</span></button>)}</div><div className="panel lesson-panel"><div className="eyebrow">SESSION {String(step+1).padStart(2,'0')}</div><h2>{lesson.title}</h2><p className="muted">{lesson.description}</p><div className="objective"><strong>이번 단계의 목표</strong><p>{lesson.objective}</p></div>{a.profile.style==='concept-first' && theory}{exercise && <CodeLab key={exercise.id} exercise={exercise} assignmentId={a.id} profile={a.profile} onSaved={record=>onUpdate({...a,practiceAttempts:[...(a.practiceAttempts || []).filter(p=>p.exerciseId!==record.exerciseId),record]})}/>}
{a.practice && !exercise && <p className="inline-error">이 실습의 실행 버전을 사용할 수 없습니다. 새 맞춤 과제를 생성해 주세요.</p>}<section className="prompt-box"><div><h3><Sparkles size={18}/> 필요하면 이 질문으로 원리를 더 살펴보세요</h3><button className="text-button" onClick={async()=>{try{await navigator.clipboard.writeText(lesson.prompt);onNotice('프롬프트를 복사했어요.');}catch{onError('복사하지 못했어요. 프롬프트를 선택해 직접 복사해 주세요.');}}}><Copy size={14}/> 복사</button></div><p>{lesson.prompt}</p></section>{a.profile.style!=='concept-first' && theory}<section className="experiment-box"><h3><FlaskConical size={18}/> 직접 바꿔 보세요</h3><p>{lesson.experiment}</p></section><section><h3>완료 전에 확인해요</h3><ul className="check-list">{lesson.checks.map((c,i)=><li key={i}><CheckCircle2 size={17}/>{c}</li>)}</ul><p className="small-note">아래 버튼은 직접 확인한 학습 진도를 기록해요.</p></section><div className="form-actions"><button className={a.completedSteps.includes(step)?'secondary':'primary'} disabled={busy} onClick={()=>void progress()}><Check size={16}/>{a.completedSteps.includes(step)?'완료 취소':'이 단계를 완료했어요'}</button>{step<a.lessons.length-1?<button className="text-button" onClick={()=>setStep(step+1)}>다음 단계 <ArrowRight size={16}/></button>:<button className="text-button" onClick={()=>setTab('quiz')}>이해도 확인하기 <ArrowRight size={16}/></button>}</div></div></div>
  <aside className="tutor panel"><div className="tutor-header"><span className="tutor-icon"><Sparkles size={20}/></span><div><h3>{aiEnabled?'AI 학습 튜터':'학습 가이드'}</h3><small>{aiEnabled?'내 경험에 맞춰 함께 생각해요':'규칙 기반 · AI 연결 전 체험'}</small></div></div><p className="small-note">현재 단계: {lesson.title}</p><div className="chat-messages" aria-live="polite">{messages.length===0 && <div className="chat-message assistant">막히는 부분이 있나요? 원리를 다시 살펴보거나, 작은 실험부터 시작해 보세요.{!aiEnabled && <p className="small-note">이 모드는 단계별 준비된 안내를 제공합니다. 자유로운 질문 답변은 AI 연결 후 사용할 수 있어요.</p>}</div>}{messages.map(m=><div key={m.id} className={`chat-message ${m.role}`}><small>{m.role==='user'?'나':m.source==='ai'?'AI 튜터':'학습 가이드'}</small><div>{m.content}</div></div>)}{chatBusy&&<p role="status" className="muted">답변을 준비하고 있어요…</p>}</div><div className="quick-questions">{['원리를 쉽게 설명해 줘','어떤 실험을 해볼까?','오류가 나면 어떻게 해?'].map(q=><button key={q} disabled={chatBusy} onClick={()=>void chat(q)}>{q}</button>)}</div><form onSubmit={e=>{e.preventDefault();void chat(question);}} className="chat-form"><textarea aria-label="튜터에게 질문" maxLength={2000} rows={3} placeholder="궁금한 점을 적어주세요…" value={question} onChange={e=>setQuestion(e.target.value)}/><button className="primary" disabled={chatBusy||!question.trim()} aria-label="질문 보내기"><Send size={16}/></button></form><p className="small-note">AI 연결 시 프로필·현재 과제·최근 대화가 전달됩니다.</p></aside></div>}
  {tab==='quiz' && <form className="panel quiz-panel" onSubmit={quiz}><span className="eyebrow">CHECK YOUR UNDERSTANDING</span><h2>만든 것을 내 말로 이해하기</h2><p className="muted">틀려도 괜찮아요. 결과는 다음 실습의 난이도를 정하는 데 사용돼요.</p>{a.quizResult&&<div className="quiz-result"><CheckCircle2 size={24}/><strong>{a.quizResult.score} / {a.quizResult.total} 정답</strong><span>{a.quizResult.score===a.quizResult.total?'원리를 잘 이해했어요. 다음 실습으로 확장해 보세요.':'해설을 읽고 다시 도전해 보세요.'}</span></div>}{a.quiz.map((q,i)=><fieldset className="quiz-question" key={i}><legend>{i+1}. {q.question}</legend>{q.options.map((option,j)=><label className={`choice ${answers[i]===j?'selected':''}`} key={j}><input type="radio" required name={`question-${i}`} checked={answers[i]===j} onChange={()=>setAnswers(prev=>prev.map((value,index)=>index===i?j:value))}/>{option}</label>)}{a.quizResult&&<div className={`quiz-feedback ${a.quizResult.feedback[i].correct?'correct':''}`}>{a.quizResult.feedback[i].correct?'정답이에요.':'다시 확인해요.'} 정답: {q.options[a.quizResult.feedback[i].answer]}<p>{a.quizResult.feedback[i].explanation}</p></div>}</fieldset>)}<button className="primary" disabled={busy||answers.some(v=>v<0)}>{busy?'확인 중…':'답변 확인하고 저장하기'}</button></form>}
  {tab==='submit' && <div className="submission-layout"><form className="panel" onSubmit={submit}><span className="eyebrow">MAKE LEARNING VISIBLE</span><h2>결과물과 배운 점을 남겨요.</h2><p className="muted">브라우저 실습은 실행 결과로 학습 기록을 남길 수 있습니다. 완성한 프로젝트가 있다면 공개 GitHub 저장소와 회고도 연결해 주세요.</p><label>GitHub 저장소 URL<input type="url" required maxLength={240} placeholder="https://github.com/username/my-project" value={url} onChange={e=>setUrl(e.target.value)}/></label><label>학습 회고<textarea required minLength={20} maxLength={3000} rows={7} placeholder="무엇을 만들었나요? 데이터는 화면에서 DB까지 어떻게 이동하나요? 막혔던 부분과 다음에 바꿔볼 점도 적어주세요. (20자 이상)" value={reflection} onChange={e=>setReflection(e.target.value)}/></label><button className="primary" disabled={busy}><Github size={17}/>{busy?'GitHub 자료를 확인하는 중…':'저장소 확인하고 회고 저장'}</button><p className="small-note">조회 결과는 최대 5분간 캐시됩니다. 코드를 실행하거나 자동 채점하지 않아요.</p></form><div className="panel"><h3>제출 확인 기록</h3>{a.submission?<><a className="repo-name" href={a.submission.url} target="_blank" rel="noreferrer">{a.submission.evidence.name} <ArrowRight size={14}/></a><dl className="evidence"><dt>README</dt><dd>{a.submission.evidence.readme?'확인됨':'없음 또는 조회 실패'}</dd><dt>기본 브랜치</dt><dd>{a.submission.evidence.defaultBranch}</dd><dt>최근 커밋</dt><dd>{a.submission.evidence.commit?.slice(0,7)||'확인할 수 없음'}</dd><dt>해당 커밋 자동 검사</dt><dd>{a.submission.evidence.workflow||'기록 없음'}</dd><dt>제출 일시</dt><dd>{new Date(a.submission.submittedAt).toLocaleString('ko-KR')}</dd></dl>{a.submission.evidence.commitMessage&&<p className="small-note">{a.submission.evidence.commitMessage}</p>}{a.submission.evidence.warnings.map(w=><p className="inline-error" key={w}>{w}</p>)}<div className="theory-box"><strong>내가 남긴 회고</strong><p className="preserve-lines">{a.submission.reflection}</p></div></>:<div className="empty-state compact"><Github size={30}/><p>저장소를 연결하면 README,<br/>최근 커밋, 자동 검사 기록을 확인할 수 있어요.</p></div>}</div></div>}
  </>;
}
